name: Release

on:
  push:
    tags: ["*"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning twine
      - name: Build and publish
        env:
          TWINE_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --build --username "__token__" --password "$TWINE_API_TOKEN"
